### ISSUE TITLE
impossible to set required_showers on velis

### ISSUE THREAD

**Issue by uowis** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#31]
```
service: aquaariston.aqua_set_data
data:
  required_showers: 2
  entity_id: water_heater.aqua_ariston_2
```
Give me this  error : 
```
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Corresponding entity_id for Ariston Aqua not found
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aquaariston/__init__.py", line 305, in set_ariston_aqua_data
    raise Exception("Corresponding entity_id for Ariston Aqua not found")
Exception: Corresponding entity_id for Ariston Aqua not found
```

**Comment by uowis** [comment]
There is my config
```
aquaariston:
  username: XXXXXXXXX
  password: !secret XXXXXXXX
  type: "velis" 
  logging: "WARNING"                  # indicates logging level ("CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG", "NOTSET"). Default is "DEBUG"
  #path: "/home/homeassistant/.homeassistant/aqua_http_data" # Forces new path for storing files. SET NEW VALUES IF "/config" IS NOT CORRECT
  polling: 1.2                        # indicates relative time for requests waiting. Increase in case of timeouts. Default is 1.0
  store_config_files: true            # indicates if to store API data in a folder
  switches:
    - eco                             # switches ECO mode
    - power                           # switches power
  binary_sensors:
    - antilegionella                  # indicates antilegionella status
    - changing_data                   # indicates ongoing configuration on server by the API
    - eco                             # indicates ECO mode status
    - heating                         # indicates ongoing heating
    - online                          # indicates API online status
    - power                           # indicates power status
    - update                          # indicates API update
  sensors:
    - antilegionella_set_temperature  # antilegionella temperature
    - current_temperature             # current temperature
    - energy_use_in_day               # energy use in last day
    - energy_use_in_month             # energy use in last week
    - energy_use_in_week              # energy use in last month
    - energy_use_in_year              # energy use in last year
    - errors                          # errors
    - mode                            # manual or time program mode
    - remaining_time                  # remaining time for heating
    - required_showers                # required amount of showers (might not work on all models)
    - required_temperature            # required temperature (simulated by API itself for some models)
    - showers                         # estimated amount of average showers
    - temperature_mode                # indicates if required temeparture is based on required temperature or required showers
    - time_program                    # time program schedule
      

```

**Comment by jccf07** [comment]
Hi, It this custom component working with ariston velis?? I am interest un buy , but i dont know if any component is working
