### ISSUE TITLE
Error loading custom_components.aquaariston

### ISSUE THREAD

**Issue by iNNPL** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#8]
Having this error in logs after HASS restart. Not able to put commends in configuration.yaml as commend is not recognized.

Logger: homeassistant.loader
Source: custom_components/aquaariston/__init__.py:1
First occurred: 12:48:51 AM (1 occurrences)
Last logged: 12:48:51 AM

Error loading custom_components.aquaariston. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 541, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/aquaariston/__init__.py", line 1, in <module>
    from . import ariston
ImportError: cannot import name 'ariston' from partially initialized module 'custom_components.aquaariston' (most likely due to a circular import) (/config/custom_components/aquaariston/__init__.py)

**Comment by kovacsguido** [comment]
This error is the same for me.

**Workaround** solution, until the developer fixes it (i.e. step back one step in the git):
- git clone the component
- git checkout f755aeee11 (this is the step back one)
- copy the current aquaariston folder into the custom_components folder in Home Assistant

It helped me temporarily.

**Comment by iNNPL** [comment]
It worked. Thank you for the solution :)

**Comment by chomupashchuk** [comment]
seems like i've accidently uploaded __init__.py from other integration. New version was uploaded. Please let me know if it works.

**Comment by kovacsguido** [comment]
Thanks, I pulled down the last version and it works!
